# Generated by Django 3.0.1 on 2020-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_First_Name', models.CharField(max_length=40)),
                ('B_Last_Name', models.CharField(max_length=40)),
                ('B_Username', models.CharField(max_length=10)),
                ('B_Gender', models.CharField(default='Others', max_length=25)),
                ('B_Phone_number', models.CharField(max_length=10)),
                ('B_E_mail', models.CharField(max_length=50)),
                ('B_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_First_Name', models.CharField(max_length=40)),
                ('O_Last_Name', models.CharField(max_length=40)),
                ('O_Username', models.CharField(max_length=10)),
                ('O_Gender', models.CharField(default='Others', max_length=25)),
                ('O_Phone_number', models.CharField(max_length=10)),
                ('O_E_mail', models.CharField(max_length=50)),
                ('O_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20000)),
                ('pub_date', models.DateField()),
                ('desc', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
